### ISSUE TITLE
v2 roadmap

### ISSUE THREAD

**Issue by pi0** [unjs/rou3#88]
v2 got delayed for a while.

The changes live in `/v2` branch: https://github.com/unjs/radix3/tree/v2

```[tasklist]
### Tasks
- [x] Support mixed params in same path segment ([#52](https://github.com/unjs/radix3/pull/52))
- [ ] Ignore query params in matching (https://github.com/unjs/radix3/pull/61)
- [x] Native support for HTTP verb/method matching (https://github.com/unjs/radix3/issues/58)
- [x] Performance analyzes (https://github.com/unjs/radix3/issues/85)
```
